-- autogenerated by BCT at 8/4/2025 3:36:50 PM
local c = {
    participantA = {
        name = "npc a",
        sprites = {
            neutral = 73040329059377,
        }
    },
    participantB = {
        name = "npc b",
        sprites = {
            neutral = 13995194992,
        }
    },
    conversation = {
        {
            subject = "participantA",
            text = "hello npc B you look great today",
            sprite = "neutral",
            voice=000
        },
        {
            subject = "participantB",
            text = "sup A, you also look fire",
            sprite = "neutral",
            voice=000
        },
        {
            subject = "participantA",
            text = "want to go on a quest together?",
            sprite = "neutral",
            voice=000
        },
        {
            subject = "participantB",
            text = "sure! i would gladly help my old friend!",
            sprite = "neutral",
            voice=000
        },
    }
}
return c